---
name: Code Checks

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [main]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.14'
          enable-cache: true
      - run: uv sync --group test
      - run: uv pip install PyQt6
      # Pyright uses dependencies of the interpreter run with the `python`.
      # But `python` doesn't run virtual env interpreter when PATH is default.
      # Override PATH to use virtual env interpreter.
      # This change makes pyright use dependencies of virtual env interpreter.
      - name: Set uv virtual env path to PATH
        run: echo ${{ github.workspace }}/.venv/bin >> $GITHUB_PATH
      - uses: jakebailey/pyright-action@v3
