---
name: tests

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [main]

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:  # Test each python and Qt-lib only once on each os.
        os: [ubuntu-latest, macOS-latest, windows-latest]
        py: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
        include:
          - {py: '3.8', qt: PySide6-Essentials}
          - {py: '3.9', qt: PyQt6}
          - {py: '3.10', qt: PySide6-Essentials}
          - {py: '3.11', qt: PyQt6}
          - {py: '3.12', qt: PySide6-Essentials}
          - {py: '3.13', qt: PySide6-Essentials}
          - {py: '3.14', qt: PySide6-Essentials}
    runs-on: ${{ matrix.os }}
    name: pytest (${{ matrix.os }}, ${{ matrix.py }}, ${{ matrix.qt }})
    env:
      QT_QPA_PLATFORM: offscreen
    defaults:
      run:
        shell: bash  # for poetry in PATH

    steps:
      - uses: actions/checkout@v6
      - uses: tlambert03/setup-qt-libs@v1
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - uses: snok/install-poetry@v1
        with:
          version: 1.8.5   # Last version compatible with python 3.8
          virtualenvs-create: true
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: >-
            ${{ runner.os }}-py${{ matrix.py }}-${{ matrix.qt }}-poetry-${{
            hashFiles('**/poetry.lock') }}
      - run: poetry install --only github-actions,test,main
      - run: poetry run pip install -U ${{ matrix.qt }}

      - run: >-
          poetry run pytest tests --color=yes
          --cov=qdarktheme
          --cov=tests
          --cov-report=term-missing
          --cov-report=xml

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Capture WidgetGallery img
        run: >-
          poetry run python ./tools/capture.py
          --name ${{runner.os}}-py${{matrix.py}}-${{matrix.qt}}

      - uses: actions/upload-artifact@v7
        with:
          name: screenshots-${{ runner.os }}-py${{ matrix.py }}-${{ matrix.qt }}
          path: ./*.png

  pytest-without-qt:
    strategy:
      fail-fast: false
      matrix:  # Python version does not affect tests without Qt.
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-py3.14-poetry-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install --only github-actions,test,main

      - run: >-
          poetry run pytest --color=yes
          --cov=qdarktheme
          --cov=tests
          --cov-report=term-missing
          --cov-report=xml
          --ignore=tests/test_widget_gallery.py
          --ignore=tests/test_qdarktheme_with_qt.py
          -p no:pytest-qt

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  PyInstaller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - uses: snok/install-poetry@v1
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: >-
            ${{ runner.os }}-py3.14-PyInstaller-poetry-${{
            hashFiles('**/poetry.lock') }}
      - run: poetry install --only main
      - run: poetry run pip install -U PyInstaller

      - name: Make test file
        run: |
          cat <<'EOL' >> test.py
          import qdarktheme
          qdarktheme.load_stylesheet('auto')
          EOL
          cat -n test.py

      - run: poetry run python -m PyInstaller test.py -n test_app -F
      - run: ./dist/test_app
